require "json"
require "yaml"

module DesignTokens
  class Compiler
    ROOT = Rails.root.join("config/design_tokens")
    SOURCE = "tokens.yml"
    SCHEMA = "tokens.schema.json"
    CSS_OUTPUT = Rails.root.join("app/assets/stylesheets/design_tokens.css")
    RUBY_OUTPUT = Rails.root.join("lib/design_tokens/generated.rb")
    JSON_OUTPUTS = {
      "base" => "base.json",
      "light" => "light.json",
      "dark" => "dark.json"
    }.freeze

    def initialize(root: ROOT, css_output: CSS_OUTPUT, ruby_output: RUBY_OUTPUT)
      @root = root
      @css_output = css_output
      @ruby_output = ruby_output
    end

    def compile
      document = token_document
      base = document.fetch("base")
      light = document.dig("themes", "light")
      dark = document.dig("themes", "dark")

      <<~CSS
        /* Generated by DesignTokens::Compiler. Do not edit directly. */
        :root,
        [data-theme="light"] {
        #{declarations(base.merge(light))}
          color-scheme: light;
        }

        [data-theme="dark"] {
        #{declarations(base.merge(dark))}
          color-scheme: dark;
        }
      CSS
    end

    def write!
      outputs.each { |path, content| path.write(content) }
    end

    def current?
      outputs.all? { |path, content| path.exist? && path.read == content }
    end

    private

    def outputs
      document = token_document
      themes = document.fetch("themes")

      {
        @css_output => compile,
        @ruby_output => ruby_output(document),
        @root.join(JSON_OUTPUTS.fetch("base")) => json_output(document.fetch("base")),
        @root.join(JSON_OUTPUTS.fetch("light")) => json_output(themes.fetch("light")),
        @root.join(JSON_OUTPUTS.fetch("dark")) => json_output(themes.fetch("dark"))
      }
    end

    def token_document
      document = YAML.safe_load(
        @root.join(SOURCE).read,
        permitted_classes: [],
        permitted_symbols: [],
        aliases: false
      )

      unless document.is_a?(Hash) && document.key?("version") && document.key?("base") && document.key?("themes")
        raise ArgumentError, "Design token YAML must include top-level 'version', 'base', and 'themes' sections."
      end

      validate_against_schema!(document, JSON.parse(@root.join(SCHEMA).read))
      validate_theme_keys!(document.dig("themes", "light"), document.dig("themes", "dark"))
      document
    rescue Psych::Exception => error
      raise ArgumentError, "Invalid design token YAML: #{error.message}"
    end

    def validate_against_schema!(value, schema, path = "$")
      expected_type = schema["type"]
      valid_type = case expected_type
      when "object" then value.is_a?(Hash)
      when "string" then value.is_a?(String)
      when "integer" then value.is_a?(Integer)
      else true
      end
      raise ArgumentError, "#{path} must be a #{expected_type}" unless valid_type

      if schema.key?("const") && value != schema["const"]
        raise ArgumentError, "#{path} must equal #{schema['const'].inspect}"
      end

      return unless value.is_a?(Hash)

      Array(schema["required"]).each do |key|
        raise ArgumentError, "#{path}.#{key} is required" unless value.key?(key)
      end

      properties = schema.fetch("properties", {})
      patterns = schema.fetch("patternProperties", {})
      value.each do |key, child|
        child_schema = properties[key] || patterns.find { |pattern, _| Regexp.new(pattern).match?(key) }&.last
        if child_schema
          validate_against_schema!(child, child_schema, "#{path}.#{key}")
        elsif schema["additionalProperties"] == false
          raise ArgumentError, "#{path}.#{key} is not allowed"
        end
      end

      minimum = schema["minProperties"]
      raise ArgumentError, "#{path} must contain at least #{minimum} entries" if minimum && value.size < minimum
    end

    def validate_theme_keys!(light, dark)
      return if light.keys.sort == dark.keys.sort

      raise ArgumentError, "Light and dark themes must define identical token keys"
    end

    def json_output(tokens)
      "#{JSON.pretty_generate(tokens.sort.to_h)}\n"
    end

    def ruby_output(document)
      base = ruby_hash(document.fetch("base"))
      light = ruby_hash(document.dig("themes", "light"))
      dark = ruby_hash(document.dig("themes", "dark"))

      <<~RUBY
        # frozen_string_literal: true

        # Generated by DesignTokens::Compiler. Do not edit directly.
        module DesignTokens
          module Generated
            VERSION = #{document.fetch('version')}
            BASE = #{base}.freeze
            THEMES = {
              "light" => #{light}.freeze,
              "dark" => #{dark}.freeze
            }.freeze
          end
        end
      RUBY
    end

    def ruby_hash(tokens)
      entries = tokens.sort.map { |key, value| "#{key.inspect} => #{value.inspect}" }
      "{ #{entries.join(', ')} }"
    end

    def declarations(tokens, indent: 2)
      prefix = " " * indent
      tokens.sort.map { |name, value| "#{prefix}--#{name.tr('.', '-')}: #{value};" }.join("\n")
    end
  end
end
