require "json"

module DesignTokens
  class Compiler
    ROOT = Rails.root.join("config/design_tokens")
    OUTPUT = Rails.root.join("app/assets/stylesheets/design_tokens.css")

    def initialize(root: ROOT, output: OUTPUT)
      @root = root
      @output = output
    end

    def compile
      base = read("base.json")
      light = read("light.json")
      dark = read("dark.json")
      validate_theme_keys!(light, dark)

      <<~CSS
        /* Generated by DesignTokens::Compiler. Do not edit directly. */
        :root,
        [data-theme="light"] {
        #{declarations(base.merge(light))}
          color-scheme: light;
        }

        [data-theme="dark"] {
        #{declarations(base.merge(dark))}
          color-scheme: dark;
        }

        @media (prefers-color-scheme: dark) {
          :root:not([data-theme]) {
        #{declarations(base.merge(dark), indent: 4)}
            color-scheme: dark;
          }
        }
      CSS
    end

    def write!
      @output.write(compile)
    end

    def current?
      @output.exist? && @output.read == compile
    end

    private

    def read(filename)
      JSON.parse(@root.join(filename).read)
    end

    def validate_theme_keys!(light, dark)
      return if light.keys.sort == dark.keys.sort

      raise ArgumentError, "Light and dark themes must define identical token keys"
    end

    def declarations(tokens, indent: 2)
      prefix = " " * indent
      tokens.sort.map { |name, value| "#{prefix}--#{name.tr('.', '-')}: #{value};" }.join("\n")
    end
  end
end
