# frozen_string_literal: true

# Generated by DesignTokens::Compiler. Do not edit directly.
module DesignTokens
  module Generated
    VERSION = 1
    BASE = { "control.height" => "2.75rem", "font.family.body" => "Inter, ui-sans-serif, system-ui, sans-serif", "font.family.heading" => "Manrope, Inter, ui-sans-serif, system-ui, sans-serif", "font.family.mono" => "\"JetBrains Mono\", \"SFMono-Regular\", Consolas, monospace", "font.family.sans" => "Inter, ui-sans-serif, system-ui, sans-serif", "font.size.lg" => "1.25rem", "font.size.md" => "1rem", "font.size.sm" => "0.875rem", "font.weight.medium" => "500", "font.weight.regular" => "400", "font.weight.semibold" => "600", "line.height.body" => "1.5", "line.height.code" => "1.45", "line.height.heading" => "1.2", "radius.lg" => "0.75rem", "radius.md" => "0.5rem", "radius.sm" => "0.25rem", "shadow.sm" => "0 1px 2px rgb(15 23 42 / 0.08)", "space.lg" => "1.5rem", "space.md" => "1rem", "space.sm" => "0.5rem", "space.xl" => "2rem", "space.xs" => "0.25rem", "transition.fast" => "120ms ease" }.freeze
    THEMES = {
      "light" => { "color.background" => "#f8fafc", "color.border" => "#cbd5e1", "color.danger" => "#b91c1c", "color.focus" => "#2563eb", "color.on-primary" => "#ffffff", "color.primary" => "#1d4ed8", "color.primary.hover" => "#1e40af", "color.success" => "#15803d", "color.surface" => "#ffffff", "color.surface.subtle" => "#f1f5f9", "color.text" => "#0f172a", "color.text.muted" => "#475569" }.freeze,
      "dark" => { "color.background" => "#0f172a", "color.border" => "#475569", "color.danger" => "#fca5a5", "color.focus" => "#93c5fd", "color.on-primary" => "#0f172a", "color.primary" => "#60a5fa", "color.primary.hover" => "#93c5fd", "color.success" => "#86efac", "color.surface" => "#1e293b", "color.surface.subtle" => "#334155", "color.text" => "#f8fafc", "color.text.muted" => "#cbd5e1" }.freeze
    }.freeze
  end
end
