import { IRichTextEditor } from '../base/interface';
import { Popup } from '@syncfusion/ej2-popups';
import { AIAssistView, PromptModel } from '@syncfusion/ej2-interactive-chat';
import { ServiceLocator } from '../services';
/**
 * Provides AI Assistant functionalities to the Rich Text Editor.
 * Inject this class as a module to access its features.
 */
export declare class AIAssistant {
    private parent;
    protected locator: ServiceLocator;
    private rendererFactory;
    private isDestroyed;
    queryPopup: Popup;
    assistView: AIAssistView;
    private blockNodes;
    private currentSelection;
    private currentAction;
    private lastResponse;
    private historyDropDownButton;
    private historyIconButton;
    private element;
    private isRendered;
    private allPrompts;
    private toolTip;
    private assistViewEditArea;
    private menu;
    private menuDropDown;
    private draggable;
    private dragged;
    private L10n;
    private handlePopupEscapeBoundFn;
    private isProcessWholeEditorContent;
    private shouldProcessResponse;
    constructor(parent: IRichTextEditor, serviceLocator: ServiceLocator);
    private addEventListener;
    private onKeyDown;
    private onToolbarClick;
    private onMenuItemSelect;
    private showAIQueryPopup;
    private updateAIQueryButtonActiveState;
    private render;
    private renderAssistView;
    private onAssitantToolbarClick;
    private onPromptRequest;
    private streamResponse;
    private parseMarkdown;
    private parsePromptResponses;
    private handleStopResponse;
    hideAIQueryPopup(): void;
    private addEditorPromptCollection;
    clearAIPromptHistory(): void;
    private updateCurrentSelection;
    private getModuleName;
    private removeEventListener;
    private refreshPosition;
    destroy(): void;
    getPromptHistory(): PromptModel[];
    executePrompt(prompt: string): void;
    scrollToBottom(): void;
    addPromptResponse(outputResponse: string | Object, isFinalUpdate?: boolean): void;
    private updateHistoryButtonStatus;
    private appendElement;
    showQueryPopup(event?: Event): void;
    private handlePopupEscape;
    private renderMenuButton;
    private renderHistoryDropDownButton;
    private handleHistoryButtonClick;
    private getToolbarItems;
    private getHeaderToolbarItem;
    private getPromptToolbarItem;
    private getReponseToolbarItem;
    private getQueryPopupOffsetY;
    private onPropertyChanged;
    private getHistoryDropDownItem;
    private renderTooltip;
    private setEditAreaRangeAndFocus;
    private bindOnEnd;
    private handleInsertContent;
    private beforeMenuOpen;
    private beforeMenuClose;
    private triggerBeforePopupOpenCloseEvent;
    private updateCssClass;
    private enableDisableHistoryToolbarButton;
}
