# frozen_string_literal: true

require "digest"
require "fileutils"
require "json"
require "pathname"

module RepositoryIntelligence
  class AiArtifactGenerator
    Result = Data.define(:files, :quality)

    def initialize(repository_path:, graph:, contracts:, output_directory:)
      @repository_path = Pathname(repository_path).realpath
      @graph = graph
      @contracts = contracts
      @output_directory = Pathname(output_directory)
    end

    def generate
      files = {}
      files["AI_CONTEXT.md"] = global_context
      module_groups.each do |name, nodes|
        files["modules/#{slug(name)}/AI_CONTEXT.md"] = module_context(name, nodes)
      end
      files["architecture.md"] = architecture_document
      files["dependencies.md"] = dependency_document
      files["impact-index.md"] = impact_document
      files["documentation-quality.json"] = JSON.pretty_generate(quality_report(files)) << "\n"
      Result.new(files:, quality: quality_report(files))
    end

    def write
      result = generate
      result.files.each do |relative, content|
        path = output_directory.join(relative)
        path.dirname.mkpath
        path.write(content)
        path.dirname.join("#{path.basename}.sha256").write("#{Digest::SHA256.hexdigest(content)}  #{path.basename}\n")
      end
      result
    end

    def validate
      generated = generate.files
      generated.filter_map do |relative, content|
        path = output_directory.join(relative)
        next "missing generated artifact: #{relative}" unless path.file?
        next if path.read == content

        "stale generated artifact: #{relative}"
      end
    end

    private

    attr_reader :repository_path, :graph, :contracts, :output_directory

    def module_groups
      graph.nodes.values.reject { |node| node.type == "document" }.group_by do |node|
        node.name.to_s.split("::").first.presence || "Platform"
      end.sort.to_h
    end

    def global_context
      <<~MARKDOWN
        # Generated AI Context

        > Generated by `ruby bin/repository-intelligence generate`. Do not edit manually.

        ## Repository purpose

        Provider-neutral Rails platform with architecture, governance, security, privacy, tenancy, contracts, playbooks and MCP-accessible repository intelligence.

        ## Current graph

        - Nodes: #{graph.nodes.size}
        - Edges: #{graph.edges.size}
        - Modules: #{module_groups.size}
        - Contracts: #{contracts.size}

        ## Engineering invariants

        - Preserve tenant boundaries and authorization checks.
        - Keep generated artifacts deterministic and synchronized with source.
        - Use registered playbooks and bounded tools; never introduce arbitrary evaluation.
        - Update tests, contracts and documentation with public behavior changes.

        ## Module index

        #{module_groups.keys.map { |name| "- [#{name}](modules/#{slug(name)}/AI_CONTEXT.md)" }.join("\n")}
      MARKDOWN
    end

    def module_context(name, nodes)
      paths = nodes.filter_map(&:path).sort
      related_edges = graph.edges.select { |edge| nodes.any? { |node| [edge.from, edge.to].include?(node.id) } }
      contract = contracts.find { |item| item.fetch("id", "").casecmp?(slug(name)) }
      <<~MARKDOWN
        # #{name} AI Context

        > Generated artifact. Source changes must be followed by regeneration.

        ## Responsibilities

        #{nodes.group_by(&:type).sort.map { |type, values| "- #{type}: #{values.map(&:name).sort.join(', ')}" }.join("\n")}

        ## Source paths

        #{paths.map { |path| "- `#{path}`" }.join("\n")}

        ## Relationships

        #{related_edges.first(50).map { |edge| "- `#{edge.from}` —#{edge.type}→ `#{edge.to}`" }.join("\n")}

        ## Contract

        #{contract ? JSON.pretty_generate(contract) : "No dedicated machine-readable contract is currently registered."}

        ## Change checklist

        - Run impact analysis for affected nodes.
        - Preserve security, privacy and tenant invariants.
        - Update required tests and public contracts.
        - Regenerate repository intelligence artifacts.
      MARKDOWN
    end

    def architecture_document
      <<~MARKDOWN
        # Generated Architecture Overview

        > Generated from the normalized governance graph.

        ## Composition

        #{graph.nodes.values.group_by(&:type).sort.map { |type, nodes| "- #{type}: #{nodes.size}" }.join("\n")}

        ## Diagram

        ```mermaid
        graph LR
        #{module_groups.keys.map { |name| "  #{slug(name).tr('-', '_')}[#{name}]" }.join("\n")}
        ```

        ## Contracts

        #{contracts.map { |contract| "- `#{contract.fetch('id')}` v#{contract.fetch('version')}" }.join("\n")}
      MARKDOWN
    end

    def dependency_document
      edges = graph.edges.group_by(&:type).sort
      <<~MARKDOWN
        # Generated Dependency Report

        #{edges.map { |type, values| "## #{type}\n\n#{values.first(100).map { |edge| "- `#{edge.from}` → `#{edge.to}`" }.join("\n")}" }.join("\n\n")}
      MARKDOWN
    end

    def impact_document
      important = graph.nodes.values.select { |node| %w[model controller job policy].include?(node.type) }.sort_by(&:id)
      <<~MARKDOWN
        # Generated Impact Index

        #{important.map { |node| "- `#{node.id}`: #{graph.impact(node.id, depth: 2).map(&:id).sort.join(', ')}" }.join("\n")}
      MARKDOWN
    end

    def quality_report(files)
      documented_nodes = graph.nodes.values.count { |node| graph.edges.any? { |edge| edge.from == node.id && edge.type == "DOCUMENTED_BY" } }
      public_nodes = graph.nodes.values.count { |node| %w[controller model job policy].include?(node.type) }
      score = public_nodes.zero? ? 100 : ((documented_nodes.to_f / public_nodes) * 100).round
      {
        schema_version: "1.0",
        score:,
        generated_files: files.size,
        public_nodes:,
        documented_nodes:,
        findings: score == 100 ? [] : ["#{public_nodes - documented_nodes} public nodes lack explicit documentation edges"]
      }
    end

    def slug(value)
      value.to_s.gsub(/([a-z\d])([A-Z])/, "\\1-\\2").downcase.gsub(/[^a-z0-9]+/, "-").gsub(/\A-|\z/, "")
    end
  end
end
