pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "syncfusion_license", to: "syncfusion_license.js"

# Syncfusion EJ2 — vanilla JS ESM packages (extracted from offline zip via bin/extract_syncfusion_assets)
pin "@syncfusion/ej2-base",          to: "syncfusion/ej2-base.es2015.js"
pin "@syncfusion/ej2-data",          to: "syncfusion/ej2-data.es2015.js"
pin "@syncfusion/ej2-grids",         to: "syncfusion/ej2-grids.es2015.js"
pin "@syncfusion/ej2-inputs",        to: "syncfusion/ej2-inputs.es2015.js"
pin "@syncfusion/ej2-dropdowns",     to: "syncfusion/ej2-dropdowns.es2015.js"
pin "@syncfusion/ej2-calendars",     to: "syncfusion/ej2-calendars.es2015.js"
pin "@syncfusion/ej2-buttons",       to: "syncfusion/ej2-buttons.es2015.js"
pin "@syncfusion/ej2-popups",        to: "syncfusion/ej2-popups.es2015.js"
pin "@syncfusion/ej2-lists",         to: "syncfusion/ej2-lists.es2015.js"
pin "@syncfusion/ej2-navigations",   to: "syncfusion/ej2-navigations.es2015.js"
pin "@syncfusion/ej2-notifications", to: "syncfusion/ej2-notifications.es2015.js"
pin "@syncfusion/ej2-excel-export",  to: "syncfusion/ej2-excel-export.es2015.js"
pin "@syncfusion/ej2-pdf-export",    to: "syncfusion/ej2-pdf-export.es2015.js"
pin "@syncfusion/ej2-splitbuttons",  to: "syncfusion/ej2-splitbuttons.es2015.js"
pin "@syncfusion/ej2-file-utils",    to: "syncfusion/ej2-file-utils.es2015.js"
pin "@syncfusion/ej2-compression",   to: "syncfusion/ej2-compression.es2015.js"
